// Copyright 2007 Stjepan Rajko.
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)_cpp_copyright_

$template_start$
$template_copyright$

namespace boost {

/** \mainpage

This is generated by doxygen directly.

It includes things such as a \ref page_related, <a href="modules.html">modules/groups</a>, automatically
generated \ref todo and \ref bug.

\include example.cpp

*/

/** \page page_related Related Page
This is a doxygen related page.
*/

/** \defgroup group_nothing Classes that do nothing.
This group contains classes that do nothing.
*/

}